CONFIG_PM=y
CONFIG_PM_DEVICE=y

# Use RTT for debug so UART does not prevent deep sleep
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n

CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=0
