CONFIG_PRINTK=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=0
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_MAIN_STACK_SIZE=2048

# Custom Kconfig options defined in ./Kconfig
CONFIG_DAY4_GREETING="Kconfig is working!"
CONFIG_DAY4_SLEEP_INTERVAL_MS=500
