CONFIG_I2C=y

# USB CDC-ACM
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="KXTJ3 Accel Shell"
CONFIG_USB_DEVICE_VID=0x2FE3
CONFIG_USB_DEVICE_PID=0x0102
CONFIG_USB_CDC_ACM=y
CONFIG_UART_LINE_CTRL=y
CONFIG_UART_CONSOLE=y

# Shell over USB serial
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_UART=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=0
